server:
  port: 8080
spring:  profiles:    active:    - staging
---
spring:  profiles: local
  kafka:
    template:      default-topic: library-events    producer:      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:        acks: all
        retries: 10
    admin:      properties:        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
        
---
spring:
  profiles: staging
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9095,localhost:9096,localhost:9097
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      ssl:        trust-store-location: file:E:/spring-project/ssl-files/server.truststore.jks
        trust-store-password: Pass@123
        key-store-location: file:E:/spring-project/ssl-files/server.keystore.jks
        key-store-password: Pass@123
      properties:
        acks: all
        retries: 10
        security:
          protocol: SSL
        ssl.endpoint.identification.algorithm:
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094        
      
  